name: Generate readme file on push
run-name: Generating readme file
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'other/'
      - '.github/'
      - '.gitignore'
      - '.LICENSE.txt'
      - 'README.md'
      - 'output.xlsx'
jobs:
  Generate-readme-file:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: check out repository code
        uses: actions/checkout@v4
        with:
          ref: main
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Remove previous readme file
        run: rm ${{ github.workspace }}/README.md
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
      - name: execute py script
        run: python other/scripts/readme_generator.py
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: commit files
        run: |
          git config --local user.email "simon.pusterhofer@avl.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automatic creation of readme file after commit on main branch on ${{ steps.date.outputs.date }}"
          git push
      - run: echo "Job finished with status ${{ job.status }}."
